xWARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.8.102:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on /status [GET]
Traceback (most recent call last):
  File "/home/fraganya/anaconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fraganya/anaconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fraganya/anaconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fraganya/anaconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 20, in healthcheck
    current_time = datetime.strftime("%H:%M:%S")
TypeError: descriptor 'strftime' for 'datetime.date' objects doesn't apply to a 'str' object
INFO:werkzeug:127.0.0.1 - - [17/Jun/2021 09:00:19] "[35m[1mGET /status HTTP/1.1[0m" 500 -
ERROR:app:Exception on /status [GET]
Traceback (most recent call last):
  File "/home/fraganya/anaconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fraganya/anaconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fraganya/anaconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fraganya/anaconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 20, in healthcheck
    current_time = datetime.now().strftime("%H:%M:%S")
TypeError: descriptor 'strftime' for 'datetime.date' objects doesn't apply to a 'str' object
INFO:werkzeug:127.0.0.1 - - [17/Jun/2021 09:00:57] "[35m[1mGET /status HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.8.102:5000/ (Press CTRL+C to quit)
INFO:app:	[09:01:01] /Status 	Status request successful.
INFO:werkzeug:127.0.0.1 - - [17/Jun/2021 09:01:01] "GET /status HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.8.102:5000/ (Press CTRL+C to quit)
INFO:app:	[09:02:59] /Status 	Status request successful.
INFO:werkzeug:127.0.0.1 - - [17/Jun/2021 09:02:59] "GET /status HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.8.102:5000/ (Press CTRL+C to quit)
INFO:app:	[09:04:21] /Status 	Status request successful.
INFO:werkzeug:127.0.0.1 - - [17/Jun/2021 09:04:21] "GET /status HTTP/1.1" 200 -
INFO:app:	[09:04:25] /Metric 	Metric request successful.
INFO:werkzeug:127.0.0.1 - - [17/Jun/2021 09:04:25] "GET /metrics HTTP/1.1" 200 -
INFO:app:	[09:04:33] / 	/ Index request successful.
INFO:werkzeug:127.0.0.1 - - [17/Jun/2021 09:04:33] "GET / HTTP/1.1" 200 -
